Repository jaoafa/jaoweb, pull requests merged in 2021-12, with the labels that each got.

#140 fix(desktop-header): #2 PC版グローバルナビゲーションボタン押下後に閉じる
  components/TheHeader.vue
  components/TheHeaderExpanded.vue
  components/TheHeaderExpandedDesktop.vue
Labels: ♻improvement

#141 fix(mobile-header): #9 グローバルナビゲーション第1階層押下時に閉じるように
  components/TheHeaderExpandedMobile.vue
Labels: ♻improvement

#145 feat: プルリクマージ時にリリース処理するアクション追加
  .github/workflows/release.yml
Labels: ✨feature request

#146 トップページのユーザ一覧を変更
  content/blog/2018xmasevent.md
  content/blog/authors.json
  pages/index.vue
Labels: 📝documentation, ♻improvement
